language: ruby

env:
  global:
    - TRAVIS_CI=1

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1

gemfile:
  - gemfiles/rails_3.2_rspec_3.0.gemfile
  - gemfiles/rails_3.2_rspec_3.1.gemfile
  - gemfiles/rails_3.2_rspec_3.2.gemfile
  - gemfiles/rails_3.2_rspec_3.3.gemfile
  - gemfiles/rails_4.0_rspec_3.0.gemfile
  - gemfiles/rails_4.0_rspec_3.1.gemfile
  - gemfiles/rails_4.0_rspec_3.2.gemfile
  - gemfiles/rails_4.0_rspec_3.3.gemfile
  - gemfiles/rails_4.1_rspec_3.0.gemfile
  - gemfiles/rails_4.1_rspec_3.1.gemfile
  - gemfiles/rails_4.1_rspec_3.2.gemfile
  - gemfiles/rails_4.1_rspec_3.3.gemfile
  - gemfiles/rails_4.2_rspec_3.0.gemfile
  - gemfiles/rails_4.2_rspec_3.1.gemfile
  - gemfiles/rails_4.2_rspec_3.2.gemfile
  - gemfiles/rails_4.2_rspec_3.3.gemfile

before_install: gem update bundler
bundler_args: --without tools

script: bundle exec rspec -b
