language: ruby

env:
  global:
    - TRAVIS_CI=1

rvm:
  - 1.9.3
  - 2.2.1

gemfile:
  - gemfiles/rails_3.2_rspec_2.99.gemfile
  - gemfiles/rails_3.2_rspec_3.0.gemfile
  - gemfiles/rails_3.2_rspec_3.1.gemfile
  - gemfiles/rails_3.2_rspec_3.2.gemfile
  - gemfiles/rails_4.0_rspec_2.99.gemfile
  - gemfiles/rails_4.0_rspec_3.0.gemfile
  - gemfiles/rails_4.0_rspec_3.1.gemfile
  - gemfiles/rails_4.0_rspec_3.2.gemfile
  - gemfiles/rails_4.1_rspec_2.99.gemfile
  - gemfiles/rails_4.1_rspec_3.0.gemfile
  - gemfiles/rails_4.1_rspec_3.1.gemfile
  - gemfiles/rails_4.1_rspec_3.2.gemfile
  - gemfiles/rails_4.2_rspec_2.99.gemfile
  - gemfiles/rails_4.2_rspec_3.0.gemfile
  - gemfiles/rails_4.2_rspec_3.1.gemfile
  - gemfiles/rails_4.2_rspec_3.2.gemfile


bundler_args: --without tools

install:
  - gem uninstall bundler
  - gem install bundler


script: bundle exec rspec -b
