language: ruby

env:
  global:
    - TRAVIS_CI=1

rvm:
  - 1.9.3
  - 2.1.5
  - 2.0.0-preview2

gemfile:
  - rails_3.2_rspec_2.14.gemfile
  - rails_3.2_rspec_2.99.gemfile
  - rails_3.2_rspec_3.0.gemfile
  - rails_3.2_rspec_3.1.gemfile
  - rails_4.0_rspec_2.14.gemfile
  - rails_4.0_rspec_2.99.gemfile
  - rails_4.0_rspec_3.0.gemfile
  - rails_4.0_rspec_3.1.gemfile
  - rails_4.1_rspec_2.14.gemfile
  - rails_4.1_rspec_2.99.gemfile
  - rails_4.1_rspec_3.0.gemfile
  - rails_4.1_rspec_3.1.gemfile
  - rails_4.2.rc1_rspec_2.14.gemfile
  - rails_4.2.rc1_rspec_2.99.gemfile
  - rails_4.2.rc1_rspec_3.0.gemfile
  - rails_4.2.rc1_rspec_3.1.gemfile

bundler_args: --without tools

script: bundle exec rspec -b