language: ruby

env:
  global:
    - TRAVIS_CI=1

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2

gemfile:
  - gemfiles/rails_3.2_rspec_2.99.gemfile
  - gemfiles/rails_3.2_rspec_3.0.gemfile
  - gemfiles/rails_3.2_rspec_3.1.gemfile
  - gemfiles/rails_4.0_rspec_2.99.gemfile
  - gemfiles/rails_4.0_rspec_3.0.gemfile
  - gemfiles/rails_4.0_rspec_3.1.gemfile
  - gemfiles/rails_4.1_rspec_2.99.gemfile
  - gemfiles/rails_4.1_rspec_3.0.gemfile
  - gemfiles/rails_4.1_rspec_3.1.gemfile


matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.0_rspec_2.99.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.0_rspec_3.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.0_rspec_3.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.1_rspec_2.99.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.1_rspec_3.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.1_rspec_3.1.gemfile

bundler_args: --without tools

script: bundle exec rspec -b