language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - gemfiles/rails-3.2
  - gemfiles/rails-4.0
  - gemfiles/rails-4.1
  - Gemfile
bundler_args: --without tools
script: bundle exec rspec